services:
  postgres-cache:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${CACHE_DB_NAME}
      POSTGRES_USER: ${CACHE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: redis:7-alpine
  db_init:
    build:
      context: .
      dockerfile: docker/Dockerfile.db_init
    env_file:
      - .env
    depends_on:
      - postgres-cache
      - redis
    environment:
      CACHE_DB_NAME: ${CACHE_DB_NAME}
      CACHE_HOST: postgres-cache
      CACHE_USER: ${CACHE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CACHE_PORT: ${CACHE_PORT}
      CACHE_SCHEMA: ${CACHE_SCHEMA}
  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    env_file:
      - .env
    depends_on:
      - postgres-cache
      - db_init
      - redis
    environment:
      CACHE_DB_NAME: ${CACHE_DB_NAME}
      CACHE_HOST: postgres-cache
      CACHE_USER: ${CACHE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CACHE_PORT: ${CACHE_PORT}
      CACHE_SCHEMA: ${CACHE_SCHEMA}
      REDIS_HOST: redis
      AUGUR_HOST: ${AUGUR_HOST}
      AUGUR_USERNAME: ${AUGUR_USERNAME}
      AUGUR_PASSWORD: ${AUGUR_PASSWORD}
      AUGUR_DATABASE: ${AUGUR_DATABASE}
      AUGUR_SCHEMA: ${AUGUR_SCHEMA}
      AUGUR_PORT: ${AUGUR_PORT}
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    depends_on:
      - postgres-cache
      - redis
      - db_init
      - celery
    environment:
      CACHE_DB_NAME: ${CACHE_DB_NAME}
      CACHE_HOST: postgres-cache
      CACHE_USER: ${CACHE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CACHE_PORT: ${CACHE_PORT}
      CACHE_SCHEMA: ${CACHE_SCHEMA}
      REDIS_HOST: redis
      AUGUR_HOST: ${AUGUR_HOST}
      AUGUR_USERNAME: ${AUGUR_USERNAME}
      AUGUR_PASSWORD: ${AUGUR_PASSWORD}
      AUGUR_DATABASE: ${AUGUR_DATABASE}
      AUGUR_SCHEMA: ${AUGUR_SCHEMA}
      AUGUR_PORT: ${AUGUR_PORT}
    ports:
      - "4995:4995"