FROM python:3.11-alpine

# Install psycopg2 dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev

# Install Python dependencies
RUN pip install psycopg2-binary python-dotenv

# Copy the cache_manager directory
COPY cache_manager/ /app/cache_manager/

# Set working directory
WORKDIR /app

# Run the db_init script
CMD ["python", "cache_manager/db_init.py"]